// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: reading.proto

package sensorpg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Readings_CountAll_FullMethodName   = "/Readings/CountAll"
	Readings_List_FullMethodName       = "/Readings/List"
	Readings_Get_FullMethodName        = "/Readings/Get"
	Readings_Statistics_FullMethodName = "/Readings/Statistics"
	Readings_Create_FullMethodName     = "/Readings/Create"
	Readings_Update_FullMethodName     = "/Readings/Update"
	Readings_Delete_FullMethodName     = "/Readings/Delete"
)

// ReadingsClient is the client API for Readings service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Readings service provides operations for managing sensor readings
type ReadingsClient interface {
	// Counts all readings in db
	CountAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CountAllResponse, error)
	// Lists readings with pagination
	List(ctx context.Context, in *ListReadingsRequest, opts ...grpc.CallOption) (*ListReadingsResponse, error)
	// Gets a specific reading by ID
	Get(ctx context.Context, in *GetReadingRequest, opts ...grpc.CallOption) (*GetReadingResponse, error)
	// Gets statistics for readings within a time range
	Statistics(ctx context.Context, in *GetStatisticsRequest, opts ...grpc.CallOption) (*GetStatisticsResponse, error)
	// Creates a new reading
	Create(ctx context.Context, in *CreateReadingRequest, opts ...grpc.CallOption) (*CreateReadingResponse, error)
	// Updates an existing reading
	Update(ctx context.Context, in *UpdateReadingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Deletes a reading by ID
	Delete(ctx context.Context, in *DeleteReadingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type readingsClient struct {
	cc grpc.ClientConnInterface
}

func NewReadingsClient(cc grpc.ClientConnInterface) ReadingsClient {
	return &readingsClient{cc}
}

func (c *readingsClient) CountAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CountAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountAllResponse)
	err := c.cc.Invoke(ctx, Readings_CountAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readingsClient) List(ctx context.Context, in *ListReadingsRequest, opts ...grpc.CallOption) (*ListReadingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReadingsResponse)
	err := c.cc.Invoke(ctx, Readings_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readingsClient) Get(ctx context.Context, in *GetReadingRequest, opts ...grpc.CallOption) (*GetReadingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReadingResponse)
	err := c.cc.Invoke(ctx, Readings_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readingsClient) Statistics(ctx context.Context, in *GetStatisticsRequest, opts ...grpc.CallOption) (*GetStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatisticsResponse)
	err := c.cc.Invoke(ctx, Readings_Statistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readingsClient) Create(ctx context.Context, in *CreateReadingRequest, opts ...grpc.CallOption) (*CreateReadingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReadingResponse)
	err := c.cc.Invoke(ctx, Readings_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readingsClient) Update(ctx context.Context, in *UpdateReadingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Readings_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readingsClient) Delete(ctx context.Context, in *DeleteReadingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Readings_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReadingsServer is the server API for Readings service.
// All implementations must embed UnimplementedReadingsServer
// for forward compatibility.
//
// Readings service provides operations for managing sensor readings
type ReadingsServer interface {
	// Counts all readings in db
	CountAll(context.Context, *emptypb.Empty) (*CountAllResponse, error)
	// Lists readings with pagination
	List(context.Context, *ListReadingsRequest) (*ListReadingsResponse, error)
	// Gets a specific reading by ID
	Get(context.Context, *GetReadingRequest) (*GetReadingResponse, error)
	// Gets statistics for readings within a time range
	Statistics(context.Context, *GetStatisticsRequest) (*GetStatisticsResponse, error)
	// Creates a new reading
	Create(context.Context, *CreateReadingRequest) (*CreateReadingResponse, error)
	// Updates an existing reading
	Update(context.Context, *UpdateReadingRequest) (*emptypb.Empty, error)
	// Deletes a reading by ID
	Delete(context.Context, *DeleteReadingRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedReadingsServer()
}

// UnimplementedReadingsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReadingsServer struct{}

func (UnimplementedReadingsServer) CountAll(context.Context, *emptypb.Empty) (*CountAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountAll not implemented")
}
func (UnimplementedReadingsServer) List(context.Context, *ListReadingsRequest) (*ListReadingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedReadingsServer) Get(context.Context, *GetReadingRequest) (*GetReadingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedReadingsServer) Statistics(context.Context, *GetStatisticsRequest) (*GetStatisticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Statistics not implemented")
}
func (UnimplementedReadingsServer) Create(context.Context, *CreateReadingRequest) (*CreateReadingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedReadingsServer) Update(context.Context, *UpdateReadingRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedReadingsServer) Delete(context.Context, *DeleteReadingRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedReadingsServer) mustEmbedUnimplementedReadingsServer() {}
func (UnimplementedReadingsServer) testEmbeddedByValue()                  {}

// UnsafeReadingsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReadingsServer will
// result in compilation errors.
type UnsafeReadingsServer interface {
	mustEmbedUnimplementedReadingsServer()
}

func RegisterReadingsServer(s grpc.ServiceRegistrar, srv ReadingsServer) {
	// If the following call panics, it indicates UnimplementedReadingsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Readings_ServiceDesc, srv)
}

func _Readings_CountAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingsServer).CountAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Readings_CountAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingsServer).CountAll(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Readings_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReadingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Readings_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingsServer).List(ctx, req.(*ListReadingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Readings_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Readings_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingsServer).Get(ctx, req.(*GetReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Readings_Statistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingsServer).Statistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Readings_Statistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingsServer).Statistics(ctx, req.(*GetStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Readings_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Readings_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingsServer).Create(ctx, req.(*CreateReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Readings_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Readings_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingsServer).Update(ctx, req.(*UpdateReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Readings_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Readings_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingsServer).Delete(ctx, req.(*DeleteReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Readings_ServiceDesc is the grpc.ServiceDesc for Readings service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Readings_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Readings",
	HandlerType: (*ReadingsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CountAll",
			Handler:    _Readings_CountAll_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Readings_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Readings_Get_Handler,
		},
		{
			MethodName: "Statistics",
			Handler:    _Readings_Statistics_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Readings_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Readings_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Readings_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reading.proto",
}
