protoc:
	protoc --go_out=../datamanager/protogen/golang/sensorpg --go_opt=paths=source_relative \
	--go-grpc_out=../datamanager/protogen/golang/sensorpg --go-grpc_opt=paths=source_relative \
	*.proto
