// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: reading.proto

package sensorpg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Get Reading
type GetReadingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadingRequest) Reset() {
	*x = GetReadingRequest{}
	mi := &file_reading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadingRequest) ProtoMessage() {}

func (x *GetReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadingRequest.ProtoReflect.Descriptor instead.
func (*GetReadingRequest) Descriptor() ([]byte, []int) {
	return file_reading_proto_rawDescGZIP(), []int{0}
}

func (x *GetReadingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetReadingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Temperature   float64                `protobuf:"fixed64,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity      float64                `protobuf:"fixed64,3,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Tvoc          uint32                 `protobuf:"varint,4,opt,name=tvoc,proto3" json:"tvoc,omitempty"`
	ECo2          uint32                 `protobuf:"varint,5,opt,name=e_co2,json=eCo2,proto3" json:"e_co2,omitempty"`
	RawHw         uint32                 `protobuf:"varint,6,opt,name=raw_hw,json=rawHw,proto3" json:"raw_hw,omitempty"`
	RawEthanol    uint32                 `protobuf:"varint,7,opt,name=raw_ethanol,json=rawEthanol,proto3" json:"raw_ethanol,omitempty"`
	Pm_25         float64                `protobuf:"fixed64,8,opt,name=pm_25,json=pm25,proto3" json:"pm_25,omitempty"`
	FireAlarm     uint32                 `protobuf:"varint,9,opt,name=fire_alarm,json=fireAlarm,proto3" json:"fire_alarm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadingResponse) Reset() {
	*x = GetReadingResponse{}
	mi := &file_reading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadingResponse) ProtoMessage() {}

func (x *GetReadingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadingResponse.ProtoReflect.Descriptor instead.
func (*GetReadingResponse) Descriptor() ([]byte, []int) {
	return file_reading_proto_rawDescGZIP(), []int{1}
}

func (x *GetReadingResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetReadingResponse) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GetReadingResponse) GetHumidity() float64 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *GetReadingResponse) GetTvoc() uint32 {
	if x != nil {
		return x.Tvoc
	}
	return 0
}

func (x *GetReadingResponse) GetECo2() uint32 {
	if x != nil {
		return x.ECo2
	}
	return 0
}

func (x *GetReadingResponse) GetRawHw() uint32 {
	if x != nil {
		return x.RawHw
	}
	return 0
}

func (x *GetReadingResponse) GetRawEthanol() uint32 {
	if x != nil {
		return x.RawEthanol
	}
	return 0
}

func (x *GetReadingResponse) GetPm_25() float64 {
	if x != nil {
		return x.Pm_25
	}
	return 0
}

func (x *GetReadingResponse) GetFireAlarm() uint32 {
	if x != nil {
		return x.FireAlarm
	}
	return 0
}

// List Readings
type ListReadingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readings      []*GetReadingResponse  `protobuf:"bytes,1,rep,name=readings,proto3" json:"readings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReadingsResponse) Reset() {
	*x = ListReadingsResponse{}
	mi := &file_reading_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReadingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReadingsResponse) ProtoMessage() {}

func (x *ListReadingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reading_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReadingsResponse.ProtoReflect.Descriptor instead.
func (*ListReadingsResponse) Descriptor() ([]byte, []int) {
	return file_reading_proto_rawDescGZIP(), []int{2}
}

func (x *ListReadingsResponse) GetReadings() []*GetReadingResponse {
	if x != nil {
		return x.Readings
	}
	return nil
}

// Create Reading
type CreateReadingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Temperature   float64                `protobuf:"fixed64,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity      float64                `protobuf:"fixed64,3,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Tvoc          uint32                 `protobuf:"varint,4,opt,name=tvoc,proto3" json:"tvoc,omitempty"`
	ECo2          uint32                 `protobuf:"varint,5,opt,name=e_co2,json=eCo2,proto3" json:"e_co2,omitempty"`
	RawHw         uint32                 `protobuf:"varint,6,opt,name=raw_hw,json=rawHw,proto3" json:"raw_hw,omitempty"`
	RawEthanol    uint32                 `protobuf:"varint,7,opt,name=raw_ethanol,json=rawEthanol,proto3" json:"raw_ethanol,omitempty"`
	PmWt          float64                `protobuf:"fixed64,8,opt,name=pm_wt,json=pmWt,proto3" json:"pm_wt,omitempty"`
	FireAlarm     uint32                 `protobuf:"varint,9,opt,name=fire_alarm,json=fireAlarm,proto3" json:"fire_alarm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReadingRequest) Reset() {
	*x = CreateReadingRequest{}
	mi := &file_reading_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReadingRequest) ProtoMessage() {}

func (x *CreateReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reading_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReadingRequest.ProtoReflect.Descriptor instead.
func (*CreateReadingRequest) Descriptor() ([]byte, []int) {
	return file_reading_proto_rawDescGZIP(), []int{3}
}

func (x *CreateReadingRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CreateReadingRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *CreateReadingRequest) GetHumidity() float64 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *CreateReadingRequest) GetTvoc() uint32 {
	if x != nil {
		return x.Tvoc
	}
	return 0
}

func (x *CreateReadingRequest) GetECo2() uint32 {
	if x != nil {
		return x.ECo2
	}
	return 0
}

func (x *CreateReadingRequest) GetRawHw() uint32 {
	if x != nil {
		return x.RawHw
	}
	return 0
}

func (x *CreateReadingRequest) GetRawEthanol() uint32 {
	if x != nil {
		return x.RawEthanol
	}
	return 0
}

func (x *CreateReadingRequest) GetPmWt() float64 {
	if x != nil {
		return x.PmWt
	}
	return 0
}

func (x *CreateReadingRequest) GetFireAlarm() uint32 {
	if x != nil {
		return x.FireAlarm
	}
	return 0
}

type CreateReadingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReadingResponse) Reset() {
	*x = CreateReadingResponse{}
	mi := &file_reading_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReadingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReadingResponse) ProtoMessage() {}

func (x *CreateReadingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reading_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReadingResponse.ProtoReflect.Descriptor instead.
func (*CreateReadingResponse) Descriptor() ([]byte, []int) {
	return file_reading_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReadingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Update Reading
type UpdateReadingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Temperature   float64                `protobuf:"fixed64,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity      float64                `protobuf:"fixed64,3,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Tvoc          uint32                 `protobuf:"varint,4,opt,name=tvoc,proto3" json:"tvoc,omitempty"`
	ECo2          uint32                 `protobuf:"varint,5,opt,name=e_co2,json=eCo2,proto3" json:"e_co2,omitempty"`
	RawHw         uint32                 `protobuf:"varint,6,opt,name=raw_hw,json=rawHw,proto3" json:"raw_hw,omitempty"`
	RawEthanol    uint32                 `protobuf:"varint,7,opt,name=raw_ethanol,json=rawEthanol,proto3" json:"raw_ethanol,omitempty"`
	Pm_25         float64                `protobuf:"fixed64,8,opt,name=pm_25,json=pm25,proto3" json:"pm_25,omitempty"`
	FireAlarm     uint32                 `protobuf:"varint,9,opt,name=fire_alarm,json=fireAlarm,proto3" json:"fire_alarm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReadingRequest) Reset() {
	*x = UpdateReadingRequest{}
	mi := &file_reading_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReadingRequest) ProtoMessage() {}

func (x *UpdateReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reading_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReadingRequest.ProtoReflect.Descriptor instead.
func (*UpdateReadingRequest) Descriptor() ([]byte, []int) {
	return file_reading_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateReadingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateReadingRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *UpdateReadingRequest) GetHumidity() float64 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *UpdateReadingRequest) GetTvoc() uint32 {
	if x != nil {
		return x.Tvoc
	}
	return 0
}

func (x *UpdateReadingRequest) GetECo2() uint32 {
	if x != nil {
		return x.ECo2
	}
	return 0
}

func (x *UpdateReadingRequest) GetRawHw() uint32 {
	if x != nil {
		return x.RawHw
	}
	return 0
}

func (x *UpdateReadingRequest) GetRawEthanol() uint32 {
	if x != nil {
		return x.RawEthanol
	}
	return 0
}

func (x *UpdateReadingRequest) GetPm_25() float64 {
	if x != nil {
		return x.Pm_25
	}
	return 0
}

func (x *UpdateReadingRequest) GetFireAlarm() uint32 {
	if x != nil {
		return x.FireAlarm
	}
	return 0
}

type UpdateReadingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReadingResponse) Reset() {
	*x = UpdateReadingResponse{}
	mi := &file_reading_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReadingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReadingResponse) ProtoMessage() {}

func (x *UpdateReadingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reading_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReadingResponse.ProtoReflect.Descriptor instead.
func (*UpdateReadingResponse) Descriptor() ([]byte, []int) {
	return file_reading_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateReadingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Delete Reading
type DeleteReadingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReadingRequest) Reset() {
	*x = DeleteReadingRequest{}
	mi := &file_reading_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReadingRequest) ProtoMessage() {}

func (x *DeleteReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reading_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReadingRequest.ProtoReflect.Descriptor instead.
func (*DeleteReadingRequest) Descriptor() ([]byte, []int) {
	return file_reading_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteReadingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteReadingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReadingResponse) Reset() {
	*x = DeleteReadingResponse{}
	mi := &file_reading_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReadingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReadingResponse) ProtoMessage() {}

func (x *DeleteReadingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reading_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReadingResponse.ProtoReflect.Descriptor instead.
func (*DeleteReadingResponse) Descriptor() ([]byte, []int) {
	return file_reading_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteReadingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_reading_proto protoreflect.FileDescriptor

const file_reading_proto_rawDesc = "" +
	"\n" +
	"\rreading.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"#\n" +
	"\x11GetReadingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa1\x02\n" +
	"\x12GetReadingResponse\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x01R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x03 \x01(\x01R\bhumidity\x12\x12\n" +
	"\x04tvoc\x18\x04 \x01(\rR\x04tvoc\x12\x13\n" +
	"\x05e_co2\x18\x05 \x01(\rR\x04eCo2\x12\x15\n" +
	"\x06raw_hw\x18\x06 \x01(\rR\x05rawHw\x12\x1f\n" +
	"\vraw_ethanol\x18\a \x01(\rR\n" +
	"rawEthanol\x12\x13\n" +
	"\x05pm_25\x18\b \x01(\x01R\x04pm25\x12\x1d\n" +
	"\n" +
	"fire_alarm\x18\t \x01(\rR\tfireAlarm\"G\n" +
	"\x14ListReadingsResponse\x12/\n" +
	"\breadings\x18\x01 \x03(\v2\x13.GetReadingResponseR\breadings\"\xa3\x02\n" +
	"\x14CreateReadingRequest\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x01R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x03 \x01(\x01R\bhumidity\x12\x12\n" +
	"\x04tvoc\x18\x04 \x01(\rR\x04tvoc\x12\x13\n" +
	"\x05e_co2\x18\x05 \x01(\rR\x04eCo2\x12\x15\n" +
	"\x06raw_hw\x18\x06 \x01(\rR\x05rawHw\x12\x1f\n" +
	"\vraw_ethanol\x18\a \x01(\rR\n" +
	"rawEthanol\x12\x13\n" +
	"\x05pm_wt\x18\b \x01(\x01R\x04pmWt\x12\x1d\n" +
	"\n" +
	"fire_alarm\x18\t \x01(\rR\tfireAlarm\"1\n" +
	"\x15CreateReadingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xf9\x01\n" +
	"\x14UpdateReadingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x01R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x03 \x01(\x01R\bhumidity\x12\x12\n" +
	"\x04tvoc\x18\x04 \x01(\rR\x04tvoc\x12\x13\n" +
	"\x05e_co2\x18\x05 \x01(\rR\x04eCo2\x12\x15\n" +
	"\x06raw_hw\x18\x06 \x01(\rR\x05rawHw\x12\x1f\n" +
	"\vraw_ethanol\x18\a \x01(\rR\n" +
	"rawEthanol\x12\x13\n" +
	"\x05pm_25\x18\b \x01(\x01R\x04pm25\x12\x1d\n" +
	"\n" +
	"fire_alarm\x18\t \x01(\rR\tfireAlarm\"1\n" +
	"\x15UpdateReadingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"&\n" +
	"\x14DeleteReadingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteReadingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2A\n" +
	"\bReadings\x125\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x15.ListReadingsResponseBVZTgithub.com/CJovan02/IoTS/Project1-Microservices/DataManager/protogen/golang/sensorpgb\x06proto3"

var (
	file_reading_proto_rawDescOnce sync.Once
	file_reading_proto_rawDescData []byte
)

func file_reading_proto_rawDescGZIP() []byte {
	file_reading_proto_rawDescOnce.Do(func() {
		file_reading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reading_proto_rawDesc), len(file_reading_proto_rawDesc)))
	})
	return file_reading_proto_rawDescData
}

var file_reading_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_reading_proto_goTypes = []any{
	(*GetReadingRequest)(nil),     // 0: GetReadingRequest
	(*GetReadingResponse)(nil),    // 1: GetReadingResponse
	(*ListReadingsResponse)(nil),  // 2: ListReadingsResponse
	(*CreateReadingRequest)(nil),  // 3: CreateReadingRequest
	(*CreateReadingResponse)(nil), // 4: CreateReadingResponse
	(*UpdateReadingRequest)(nil),  // 5: UpdateReadingRequest
	(*UpdateReadingResponse)(nil), // 6: UpdateReadingResponse
	(*DeleteReadingRequest)(nil),  // 7: DeleteReadingRequest
	(*DeleteReadingResponse)(nil), // 8: DeleteReadingResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_reading_proto_depIdxs = []int32{
	9,  // 0: GetReadingResponse.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 1: ListReadingsResponse.readings:type_name -> GetReadingResponse
	9,  // 2: CreateReadingRequest.timestamp:type_name -> google.protobuf.Timestamp
	10, // 3: Readings.List:input_type -> google.protobuf.Empty
	2,  // 4: Readings.List:output_type -> ListReadingsResponse
	4,  // [4:5] is the sub-list for method output_type
	3,  // [3:4] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_reading_proto_init() }
func file_reading_proto_init() {
	if File_reading_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reading_proto_rawDesc), len(file_reading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reading_proto_goTypes,
		DependencyIndexes: file_reading_proto_depIdxs,
		MessageInfos:      file_reading_proto_msgTypes,
	}.Build()
	File_reading_proto = out.File
	file_reading_proto_goTypes = nil
	file_reading_proto_depIdxs = nil
}
